version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019 Preview
shallow_clone: true
before_build:
  - nuget restore
build:
  project: FolderObserver.sln
  publish_nuget: false
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: 'C:\projects\folderobserver\FolderObserver\bin\Debug\FolderObserver.exe'
  name: FolderObserver.dll
deploy:
- provider: NuGet
  api_key:
    secure: /qDdlDopI8PSfoElwGykgg==
  skip_symbols: true
  on:
    branch: master